<a href="https://colab.research.google.com/github/demoncey/01_BuildingEscape/blob/master/tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import sklearn



[przyklad](https://colab.research.google.com/drive/1XJx3f266pDeOsg6h7Y6QVWlKoxKdJ56N#scrollTo=GObK1RhbJP33)



[przyklad](https://github.com/krakowiakpawel9/machine-learning-bootcamp/blob/master/supervised/01_basics/01_preprocessing.ipynb)

In [4]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data)
df_raw



size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [5]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


In [6]:
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes


In [7]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [ ]:

df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [8]:
df


size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [10]:
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [11]:

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [12]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [13]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [15]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [21]:
pd.get_dummies(data=df).astype(int)


price  weight  bought  size_L  size_M  size_XL  color_blue  color_green  \
0    199     500       1       0       0        1           0            0   
1     89     450       0       1       0        0           0            1   
2     99     300       1       0       1        0           1            0   
3    129     380       0       1       0        0           0            1   
4     79     410       1       0       1        0           0            0   

   color_red  gender_female  gender_male  
0          1              1            0  
1          0              0            1  
2          0              0            1  
3          0              1            0  
4          1              1            0

In [22]:
pd.get_dummies(data=df, drop_first=True).astype(int)

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0    199     500       1       0        1            0          1            0
1     89     450       0       0        0            1          0            1
2     99     300       1       1        0            0          0            1
3    129     380       0       0        0            1          0            0
4     79     410       1       1        0            0          1            0

In [23]:
pd.get_dummies(data=df, drop_first=True, prefix='new').astype(int)

price  weight  bought  new_M  new_XL  new_green  new_red  new_male
0    199     500       1      0       1          0        1         0
1     89     450       0      0       0          1        0         1
2     99     300       1      1       0          0        0         1
3    129     380       0      0       0          1        0         0
4     79     410       1      1       0          0        1         0

In [27]:
df=pd.get_dummies(data=df, drop_first=True, columns=['size'])


In [29]:
df['size_M'] = df['size_M'].astype(int)
df['size_XL'] = df['size_XL'].astype(int)
df

color  gender  price  weight  bought  size_M  size_XL
0    red  female  199.0   500.0       1       0        1
1  green    male   89.0   450.0       0       0        0
2   blue    male   99.0   300.0       1       1        0
3  green  female  129.0   380.0       0       0        0
4    red  female   79.0   410.0       1       1        0

In [30]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie standardowe: 48.4768


In [31]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [32]:
from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [34]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

color  gender     price    weight  bought  size_M  size_XL
0    red  female  1.845062  1.366002       1       0        1
1  green    male -0.691898  0.623610       0       0        0
2   blue    male -0.461266 -1.603567       1       1        0
3  green  female  0.230633 -0.415740       0       0        0
4    red  female -0.922531  0.029696       1       1        0

In [35]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [36]:
le = LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df = pd.get_dummies(data=df, drop_first=True)
df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1   False     True        False       True   
1 -0.691898  0.623610       0   False    False         True      False   
2 -0.461266 -1.603567       1    True    False        False      False   
3  0.230633 -0.415740       0   False    False         True      False   
4 -0.922531  0.029696       1    True    False        False       True   

   gender_male  
0        False  
1         True  
2         True  
3        False  
4        False

In [40]:
df['size_M'] = df['size_M'].astype(int)
df['size_XL'] = df['size_XL'].astype(int)
df['color_green'] = df['color_green'].astype(int)
df['color_red'] = df['color_red'].astype(int)
df['gender_male'] = df['gender_male'].astype(int)
df


price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0